export interface MedalCount {
  g?: number; // Gold medals
  s?: number; // Silver medals
  b?: number; // Bronze medals
}

export interface OlympicData {
  [year: number]: {
    [country: string]: MedalCount;
  };
}

export const olympicData: OlympicData = {
  2020: {
    "United States": { g: 39, s: 41, b: 33 },
    "China": { g: 38, s: 32, b: 19 },
    "Japan": { g: 27, s: 14, b: 17 },
    "Great Britain": { g: 22, s: 20, b: 22 },
    "ROC": { g: 20, s: 28, b: 23 },
    "Australia": { g: 17, s: 7, b: 22 },
    "Netherlands": { g: 10, s: 12, b: 14 },
    "France": { g: 10, s: 12, b: 11 },
    "Germany": { g: 10, s: 11, b: 16 },
    "Italy": { g: 10, s: 10, b: 20 },
    "Canada": { g: 7, s: 6, b: 11 },
    "Brazil": { g: 7, s: 6, b: 8 },
    "New Zealand": { g: 7, s: 6, b: 7 },
    "Cuba": { g: 7, s: 3, b: 5 },
    "Hungary": { g: 6, s: 7, b: 7 },
    "South Korea": { g: 6, s: 4, b: 10 },
    "Poland": { g: 4, s: 5, b: 5 },
    "Czech Republic": { g: 4, s: 4, b: 3 },
    "Kenya": { g: 4, s: 4, b: 2 },
    "Norway": { g: 4, s: 2, b: 2 },
    "Jamaica": { g: 4, s: 1, b: 4 },
    "Spain": { g: 3, s: 8, b: 6 },
    "Sweden": { g: 3, s: 6, b: 0 },
    "Switzerland": { g: 3, s: 4, b: 6 },
    "Denmark": { g: 3, s: 4, b: 4 },
    "Croatia": { g: 3, s: 3, b: 2 },
    "Iran": { g: 3, s: 2, b: 2 },
    "Serbia": { g: 3, s: 1, b: 5 },
    "Belgium": { g: 3, s: 1, b: 3 },
    "Bulgaria": { g: 3, s: 1, b: 2 },
    "Slovenia": { g: 3, s: 1, b: 1 },
    "Uzbekistan": { g: 3, s: 0, b: 2 },
    "Georgia": { g: 2, s: 5, b: 1 },
    "Chinese Taipei": { g: 2, s: 4, b: 6 },
    "Turkey": { g: 2, s: 2, b: 9 },
    "Greece": { g: 2, s: 1, b: 1 },
    "Uganda": { g: 2, s: 1, b: 1 },
    "Ecuador": { g: 2, s: 1, b: 0 },
    "Ireland": { g: 2, s: 0, b: 2 },
    "Israel": { g: 2, s: 0, b: 2 },
    "Qatar": { g: 2, s: 0, b: 1 },
    "Bahamas": { g: 2, s: 0, b: 0 },
    "Kosovo": { g: 2, s: 0, b: 0 },
    "Ukraine": { g: 1, s: 6, b: 12 },
    "Belarus": { g: 1, s: 3, b: 3 },
    "Romania": { g: 1, s: 3, b: 0 },
    "Venezuela": { g: 1, s: 3, b: 0 },
    "India": { g: 1, s: 2, b: 4 },
    "Hong Kong": { g: 1, s: 2, b: 3 },
    "Philippines": { g: 1, s: 2, b: 1 },
    "Slovakia": { g: 1, s: 2, b: 1 },
    "South Africa": { g: 1, s: 2, b: 0 },
    "Austria": { g: 1, s: 1, b: 5 },
    "Egypt": { g: 1, s: 1, b: 4 },
    "Indonesia": { g: 1, s: 1, b: 3 },
    "Ethiopia": { g: 1, s: 1, b: 2 },
    "Portugal": { g: 1, s: 1, b: 2 },
    "Tunisia": { g: 1, s: 1, b: 0 },
    "Estonia": { g: 1, s: 0, b: 1 },
    "Fiji": { g: 1, s: 0, b: 1 },
    "Latvia": { g: 1, s: 0, b: 1 },
    "Thailand": { g: 1, s: 0, b: 1 },
    "Bermuda": { g: 1, s: 0, b: 0 },
    "Morocco": { g: 1, s: 0, b: 0 },
    "Puerto Rico": { g: 1, s: 0, b: 0 },
    "Colombia": { g: 0, s: 4, b: 1 },
    "Azerbaijan": { g: 0, s: 3, b: 4 },
    "Dominican Republic": { g: 0, s: 3, b: 2 },
    "Armenia": { g: 0, s: 2, b: 2 },
    "Kyrgyzstan": { g: 0, s: 2, b: 1 },
    "Mongolia": { g: 0, s: 1, b: 3 },
    "Argentina": { g: 0, s: 1, b: 2 },
    "San Marino": { g: 0, s: 1, b: 2 },
    "Jordan": { g: 0, s: 1, b: 1 },
    "Malaysia": { g: 0, s: 1, b: 1 },
    "Nigeria": { g: 0, s: 1, b: 1 },
    "Bahrain": { g: 0, s: 1, b: 0 },
    "Lithuania": { g: 0, s: 1, b: 0 },
    "Namibia": { g: 0, s: 1, b: 0 },
    "North Macedonia": { g: 0, s: 1, b: 0 },
    "Saudi Arabia": { g: 0, s: 1, b: 0 },
    "Turkmenistan": { g: 0, s: 1, b: 0 },
    "Kazakhstan": { g: 0, s: 0, b: 8 },
    "Mexico": { g: 0, s: 0, b: 4 },
    "Finland": { g: 0, s: 0, b: 2 },
    "Botswana": { g: 0, s: 0, b: 1 },
    "Burkina Faso": { g: 0, s: 0, b: 1 },
    "Ghana": { g: 0, s: 0, b: 1 },
    "Grenada": { g: 0, s: 0, b: 1 },
    "Ivory Coast": { g: 0, s: 0, b: 1 },
    "Kuwait": { g: 0, s: 0, b: 1 },
    "Moldova": { g: 0, s: 0, b: 1 },
    "Syria": { g: 0, s: 0, b: 1 },
  },
  2016: {
    "United States": { g: 46, s: 37, b: 38 },
    "Great Britain": { g: 27, s: 23, b: 17 },
    "China": { g: 26, s: 18, b: 26 },
    "Russia": { g: 19, s: 17, b: 20 },
    "Germany": { g: 17, s: 10, b: 15 },
    "Japan": { g: 12, s: 8, b: 21 },
    "France": { g: 10, s: 18, b: 14 },
    "South Korea": { g: 9, s: 3, b: 9 },
    "Italy": { g: 8, s: 12, b: 8 },
    "Australia": { g: 8, s: 11, b: 10 },
    "Netherlands": { g: 8, s: 7, b: 4 },
    "Hungary": { g: 8, s: 3, b: 4 },
    "Brazil": { g: 7, s: 6, b: 6 },
    "Spain": { g: 7, s: 4, b: 6 },
    "Kenya": { g: 6, s: 6, b: 1 },
    "Jamaica": { g: 6, s: 3, b: 2 },
    "Croatia": { g: 5, s: 3, b: 2 },
    "Cuba": { g: 5, s: 2, b: 4 },
    "New Zealand": { g: 4, s: 9, b: 5 },
    "Canada": { g: 4, s: 3, b: 15 },
    "Uzbekistan": { g: 4, s: 2, b: 7 },
    "Colombia": { g: 3, s: 2, b: 3 },
    "Switzerland": { g: 3, s: 2, b: 2 },
    "Iran": { g: 3, s: 1, b: 4 },
    "Greece": { g: 3, s: 1, b: 2 },
    "Argentina": { g: 3, s: 1, b: 0 },
    "Denmark": { g: 2, s: 6, b: 7 },
    "Sweden": { g: 2, s: 6, b: 3 },
    "South Africa": { g: 2, s: 6, b: 2 },
    "Kazakhstan": { g: 2, s: 5, b: 10 },
    "Ukraine": { g: 2, s: 5, b: 4 },
    "Serbia": { g: 2, s: 4, b: 2 },
    "Poland": { g: 2, s: 3, b: 6 },
    "North Korea": { g: 2, s: 3, b: 2 },
    "Belgium": { g: 2, s: 2, b: 2 },
    "Thailand": { g: 2, s: 2, b: 2 },
    "Slovakia": { g: 2, s: 2, b: 0 },
    "Georgia": { g: 2, s: 1, b: 4 },
    "Azerbaijan": { g: 1, s: 7, b: 10 },
    "Belarus": { g: 1, s: 4, b: 4 },
    "Turkey": { g: 1, s: 3, b: 4 },
    "Armenia": { g: 1, s: 3, b: 0 },
    "Czech Republic": { g: 1, s: 2, b: 7 },
    "Ethiopia": { g: 1, s: 2, b: 5 },
    "Slovenia": { g: 1, s: 2, b: 1 },
    "Indonesia": { g: 1, s: 2, b: 0 },
    "Romania": { g: 1, s: 1, b: 2 },
    "Bahrain": { g: 1, s: 1, b: 0 },
    "Vietnam": { g: 1, s: 1, b: 0 },
    "Chinese Taipei": { g: 1, s: 0, b: 2 },
    "Bahamas": { g: 1, s: 0, b: 1 },
    "Independent Olympic Athletes": { g: 1, s: 0, b: 1 },
    "Ivory Coast": { g: 1, s: 0, b: 1 },
    "Fiji": { g: 1, s: 0, b: 0 },
    "Jordan": { g: 1, s: 0, b: 0 },
    "Kosovo": { g: 1, s: 0, b: 0 },
    "Puerto Rico": { g: 1, s: 0, b: 0 },
    "Singapore": { g: 1, s: 0, b: 0 },
    "Tajikistan": { g: 1, s: 0, b: 0 },
    "Malaysia": { g: 0, s: 4, b: 1 },
    "Mexico": { g: 0, s: 3, b: 2 },
    "Venezuela": { g: 0, s: 2, b: 1 },
    "Algeria": { g: 0, s: 2, b: 0 },
    "Ireland": { g: 0, s: 2, b: 0 },
    "Lithuania": { g: 0, s: 1, b: 3 },
    "Bulgaria": { g: 0, s: 1, b: 2 },
    "India": { g: 0, s: 1, b: 1 },
    "Mongolia": { g: 0, s: 1, b: 1 },
    "Burundi": { g: 0, s: 1, b: 0 },
    "Grenada": { g: 0, s: 1, b: 0 },
    "Niger": { g: 0, s: 1, b: 0 },
    "Philippines": { g: 0, s: 1, b: 0 },
    "Qatar": { g: 0, s: 1, b: 0 },
    "Norway": { g: 0, s: 0, b: 4 },
    "Egypt": { g: 0, s: 0, b: 3 },
    "Tunisia": { g: 0, s: 0, b: 3 },
    "Israel": { g: 0, s: 0, b: 2 },
    "Austria": { g: 0, s: 0, b: 1 },
    "Dominican Republic": { g: 0, s: 0, b: 1 },
    "Estonia": { g: 0, s: 0, b: 1 },
    "Finland": { g: 0, s: 0, b: 1 },
    "Morocco": { g: 0, s: 0, b: 1 },
    "Nigeria": { g: 0, s: 0, b: 1 },
    "Portugal": { g: 0, s: 0, b: 1 },
    "Trinidad and Tobago": { g: 0, s: 0, b: 1 },
    "United Arab Emirates": { g: 0, s: 0, b: 1 },
  },
  2012: {
    "United States": { g: 46, s: 29, b: 29 },
    "China": { g: 38, s: 27, b: 23 },
    "Great Britain": { g: 29, s: 17, b: 19 },
    "Russia": { g: 24, s: 26, b: 32 },
    "South Korea": { g: 13, s: 8, b: 7 },
    "Germany": { g: 11, s: 19, b: 14 },
    "France": { g: 11, s: 11, b: 12 },
    "Australia": { g: 7, s: 16, b: 12 },
    "Italy": { g: 8, s: 9, b: 11 },
    "Hungary": { g: 8, s: 4, b: 5 },
    "Japan": { g: 7, s: 14, b: 17 },
    "Iran": { g: 7, s: 5, b: 1 },
    "Netherlands": { g: 6, s: 6, b: 8 },
    "New Zealand": { g: 6, s: 2, b: 5 },
    "Ukraine": { g: 6, s: 5, b: 9 },
    "Cuba": { g: 5, s: 3, b: 6 },
    "Spain": { g: 3, s: 10, b: 4 },
    "Jamaica": { g: 4, s: 4, b: 4 },
    "Czech Republic": { g: 4, s: 3, b: 3 },
    "South Africa": { g: 4, s: 1, b: 1 },
    "North Korea": { g: 4, s: 0, b: 2 },
    "Brazil": { g: 3, s: 5, b: 9 },
    "Kazakhstan": { g: 3, s: 1, b: 5 },
    "Poland": { g: 2, s: 2, b: 6 },
    "Ethiopia": { g: 3, s: 1, b: 3 },
    "Croatia": { g: 3, s: 1, b: 2 },
    "Canada": { g: 1, s: 5, b: 12 },
    "Belarus": { g: 2, s: 5, b: 5 },
    "Kenya": { g: 2, s: 4, b: 5 },
    "Denmark": { g: 2, s: 4, b: 3 },
    "Romania": { g: 2, s: 5, b: 2 },
    "Azerbaijan": { g: 2, s: 2, b: 6 },
    "Switzerland": { g: 2, s: 2, b: 0 },
    "Norway": { g: 2, s: 1, b: 1 },
    "Lithuania": { g: 2, s: 1, b: 2 },
    "Tunisia": { g: 1, s: 1, b: 1 },
    "Sweden": { g: 1, s: 4, b: 3 },
    "Colombia": { g: 1, s: 3, b: 4 },
    "Mexico": { g: 1, s: 3, b: 3 },
    "Georgia": { g: 1, s: 3, b: 3 },
    "Ireland": { g: 1, s: 1, b: 3 },
    "Argentina": { g: 1, s: 1, b: 2 },
    "Serbia": { g: 1, s: 1, b: 2 },
    "Slovenia": { g: 1, s: 1, b: 2 },
    "Trinidad and Tobago": { g: 1, s: 0, b: 3 },
    "Turkey": { g: 2, s: 2, b: 1 },
    "Dominican Republic": { g: 1, s: 1, b: 0 },
    "Chinese Taipei": { g: 1, s: 0, b: 1 },
    "Latvia": { g: 1, s: 0, b: 1 },
    "Algeria": { g: 1, s: 0, b: 0 },
    "Bahamas": { g: 1, s: 0, b: 0 },
    "Grenada": { g: 1, s: 0, b: 0 },
    "Uganda": { g: 1, s: 0, b: 0 },
    "Venezuela": { g: 1, s: 0, b: 0 },
    "Egypt": { g: 0, s: 2, b: 0 },
    "India": { g: 0, s: 2, b: 4 },
    "Mongolia": { g: 0, s: 2, b: 3 },
    "Thailand": { g: 0, s: 2, b: 1 },
    "Bulgaria": { g: 0, s: 1, b: 1 },
    "Finland": { g: 0, s: 1, b: 2 },
    "Indonesia": { g: 0, s: 1, b: 1 },
    "Slovakia": { g: 0, s: 1, b: 3 },
    "Belgium": { g: 0, s: 1, b: 2 },
    "Armenia": { g: 0, s: 1, b: 2 },
    "Estonia": { g: 0, s: 1, b: 1 },
    "Malaysia": { g: 0, s: 1, b: 1 },
    "Puerto Rico": { g: 0, s: 1, b: 1 },
    "Qatar": { g: 0, s: 0, b: 2 },
    "Greece": { g: 0, s: 0, b: 2 },
    "Singapore": { g: 0, s: 0, b: 2 },
    "Afghanistan": { g: 0, s: 0, b: 1 },
    "Bahrain": { g: 0, s: 0, b: 1 },
    "Hong Kong": { g: 0, s: 0, b: 1 },
    "Saudi Arabia": { g: 0, s: 0, b: 1 },
    "Kuwait": { g: 0, s: 0, b: 1 },
    "Morocco": { g: 0, s: 0, b: 1 },
    "Tajikistan": { g: 0, s: 0, b: 1 },
    "Vietnam": { g: 0, s: 0, b: 1 },
  },
  2008: {
    "China": { g: 48, s: 22, b: 30 },
    "United States": { g: 36, s: 38, b: 36 },
    "Russia": { g: 23, s: 21, b: 28 },
    "Great Britain": { g: 19, s: 13, b: 15 },
    "Germany": { g: 16, s: 10, b: 15 },
    "Australia": { g: 14, s: 15, b: 17 },
    "South Korea": { g: 13, s: 10, b: 8 },
    "Japan": { g: 9, s: 6, b: 10 },
    "Italy": { g: 8, s: 10, b: 10 },
    "France": { g: 7, s: 16, b: 17 },
    "Netherlands": { g: 7, s: 5, b: 4 },
    "Ukraine": { g: 7, s: 5, b: 15 },
    "Jamaica": { g: 6, s: 3, b: 2 },
    "Spain": { g: 5, s: 10, b: 3 },
    "Kenya": { g: 5, s: 5, b: 4 },
    "Belarus": { g: 4, s: 5, b: 10 },
    "Romania": { g: 4, s: 1, b: 3 },
    "Ethiopia": { g: 4, s: 1, b: 2 },
    "Canada": { g: 3, s: 9, b: 8 },
    "Poland": { g: 3, s: 6, b: 1 },
    "Hungary": { g: 3, s: 5, b: 2 },
    "Norway": { g: 3, s: 5, b: 1 },
    "Brazil": { g: 3, s: 4, b: 8 },
    "Czech Republic": { g: 3, s: 3, b: 0 },
    "Slovakia": { g: 3, s: 2, b: 1 },
    "New Zealand": { g: 3, s: 1, b: 5 },
    "Georgia": { g: 3, s: 0, b: 3 },
    "Cuba": { g: 2, s: 11, b: 11 },
    "Kazakhstan": { g: 2, s: 4, b: 7 },
    "Denmark": { g: 2, s: 2, b: 3 },
    "North Korea": { g: 2, s: 1, b: 3 },
    "Argentina": { g: 2, s: 0, b: 4 },
    "Thailand": { g: 2, s: 2, b: 2 },
    "Mongolia": { g: 2, s: 2, b: 0 },
    "Switzerland": { g: 2, s: 1, b: 4 },
    "Mexico": { g: 2, s: 0, b: 1 },
    "Turkey": { g: 1, s: 4, b: 3 },
    "Zimbabwe": { g: 1, s: 3, b: 0 },
    "Azerbaijan": { g: 1, s: 2, b: 4 },
    "Uzbekistan": { g: 1, s: 2, b: 3 },
    "Slovenia": { g: 1, s: 2, b: 2 },
    "Indonesia": { g: 1, s: 1, b: 3 },
    "Finland": { g: 1, s: 1, b: 2 },
    "Latvia": { g: 1, s: 1, b: 1 },
    "Belgium": { g: 1, s: 1, b: 0 },
    "Dominican Republic": { g: 1, s: 1, b: 0 },
    "Estonia": { g: 1, s: 1, b: 0 },
    "Portugal": { g: 1, s: 1, b: 0 },
    "India": { g: 1, s: 0, b: 2 },
    "Iran": { g: 1, s: 0, b: 1 },
    "Cameroon": { g: 1, s: 0, b: 0 },
    "Panama": { g: 1, s: 0, b: 0 },
    "Tunisia": { g: 1, s: 0, b: 0 },
    "Sweden": { g: 0, s: 4, b: 1 },
    "Croatia": { g: 0, s: 2, b: 3 },
    "Lithuania": { g: 0, s: 2, b: 3 },
    "Greece": { g: 0, s: 2, b: 2 },
    "Trinidad and Tobago": { g: 0, s: 2, b: 0 },
    "Nigeria": { g: 0, s: 1, b: 3 },
    "Austria": { g: 0, s: 1, b: 2 },
    "Ireland": { g: 0, s: 1, b: 2 },
    "Serbia": { g: 0, s: 1, b: 2 },
    "Algeria": { g: 0, s: 1, b: 1 },
    "Bahamas": { g: 0, s: 1, b: 1 },
    "Colombia": { g: 0, s: 1, b: 1 },
    "Kyrgyzstan": { g: 0, s: 1, b: 1 },
    "Morocco": { g: 0, s: 1, b: 1 },
    "Tajikistan": { g: 0, s: 1, b: 1 },
    "Chile": { g: 0, s: 1, b: 0 },
    "Ecuador": { g: 0, s: 1, b: 0 },
    "Iceland": { g: 0, s: 1, b: 0 },
    "Malaysia": { g: 0, s: 1, b: 0 },
    "Singapore": { g: 0, s: 1, b: 0 },
    "South Africa": { g: 0, s: 1, b: 0 },
    "Sudan": { g: 0, s: 0, b: 1 },
    "Vietnam": { g: 0, s: 0, b: 1 },
    "Armenia": { g: 0, s: 0, b: 6 },
    "Chinese Taipei": { g: 0, s: 0, b: 4 },
    "Afghanistan": { g: 0, s: 0, b: 1 },
    "Egypt": { g: 0, s: 0, b: 2 },
    "Israel": { g: 0, s: 0, b: 1 },
    "Mauritius": { g: 0, s: 0, b: 1 },
    "Moldova": { g: 0, s: 0, b: 1 },
    "Togo": { g: 0, s: 0, b: 1 },
    "Venezuela": { g: 0, s: 0, b: 1 },
  },
  2004: {
    "United States": { g: 35, s: 39, b: 29 },
    "China": { g: 32, s: 17, b: 14 },
    "Russia": { g: 27, s: 27, b: 38 },
    "Australia": { g: 17, s: 16, b: 16 },
    "Japan": { g: 16, s: 9, b: 12 },
    "Germany": { g: 13, s: 16, b: 20 },
    "France": { g: 11, s: 9, b: 13 },
    "Italy": { g: 10, s: 11, b: 11 },
    "South Korea": { g: 9, s: 12, b: 9 },
    "Great Britain": { g: 9, s: 9, b: 12 },
    "Cuba": { g: 9, s: 7, b: 11 },
    "Hungary": { g: 8, s: 6, b: 3 },
    "Ukraine": { g: 8, s: 5, b: 9 },
    "Romania": { g: 8, s: 5, b: 6 },
    "Greece": { g: 6, s: 6, b: 4 },
    "Brazil": { g: 5, s: 2, b: 3 },
    "Norway": { g: 5, s: 0, b: 1 },
    "Netherlands": { g: 4, s: 9, b: 9 },
    "Sweden": { g: 4, s: 2, b: 1 },
    "Spain": { g: 3, s: 11, b: 6 },
    "Canada": { g: 3, s: 6, b: 3 },
    "Turkey": { g: 3, s: 3, b: 4 },
    "Poland": { g: 3, s: 2, b: 5 },
    "New Zealand": { g: 3, s: 2, b: 0 },
    "Thailand": { g: 3, s: 1, b: 4 },
    "Belarus": { g: 2, s: 6, b: 7 },
    "Austria": { g: 2, s: 4, b: 1 },
    "Ethiopia": { g: 2, s: 3, b: 2 },
    "Iran": { g: 2, s: 2, b: 2 },
    "Slovakia": { g: 2, s: 2, b: 2 },
    "Chinese Taipei": { g: 2, s: 2, b: 1 },
    "Georgia": { g: 2, s: 2, b: 0 },
    "Bulgaria": { g: 2, s: 1, b: 9 },
    "Denmark": { g: 2, s: 1, b: 5 },
    "Jamaica": { g: 2, s: 1, b: 2 },
    "Uzbekistan": { g: 2, s: 1, b: 2 },
    "Morocco": { g: 2, s: 1, b: 0 },
    "Argentina": { g: 2, s: 0, b: 4 },
    "Chile": { g: 2, s: 0, b: 1 },
    "Kazakhstan": { g: 1, s: 4, b: 3 },
    "Kenya": { g: 1, s: 4, b: 2 },
    "Czech Republic": { g: 1, s: 3, b: 5 },
    "South Africa": { g: 1, s: 3, b: 2 },
    "Croatia": { g: 1, s: 2, b: 2 },
    "Lithuania": { g: 1, s: 2, b: 0 },
    "Egypt": { g: 1, s: 1, b: 3 },
    "Switzerland": { g: 1, s: 1, b: 3 },
    "Indonesia": { g: 1, s: 1, b: 2 },
    "Zimbabwe": { g: 1, s: 1, b: 1 },
    "Azerbaijan": { g: 1, s: 0, b: 4 },
    "Belgium": { g: 1, s: 0, b: 2 },
    "Bahamas": { g: 1, s: 0, b: 1 },
    "Israel": { g: 1, s: 0, b: 1 },
    "Cameroon": { g: 1, s: 0, b: 0 },
    "Dominican Republic": { g: 1, s: 0, b: 0 },
    "United Arab Emirates": { g: 1, s: 0, b: 0 },
    "North Korea": { g: 0, s: 4, b: 1 },
    "Latvia": { g: 0, s: 4, b: 0 },
    "Mexico": { g: 0, s: 3, b: 1 },
    "Portugal": { g: 0, s: 2, b: 1 },
    "Finland": { g: 0, s: 2, b: 0 },
    "Serbia and Montenegro": { g: 0, s: 2, b: 0 },
    "Slovenia": { g: 0, s: 1, b: 3 },
    "Estonia": { g: 0, s: 1, b: 2 },
    "Hong Kong": { g: 0, s: 1, b: 0 },
    "India": { g: 0, s: 1, b: 0 },
    "Paraguay": { g: 0, s: 1, b: 0 },
    "Colombia": { g: 0, s: 0, b: 2 },
    "Nigeria": { g: 0, s: 0, b: 2 },
    "Venezuela": { g: 0, s: 0, b: 2 },
    "Eritrea": { g: 0, s: 0, b: 1 },
    "Mongolia": { g: 0, s: 0, b: 1 },
    "Syria": { g: 0, s: 0, b: 1 },
    "Trinidad and Tobago": { g: 0, s: 0, b: 1 },
  },
  2000: {
    "United States": { g: 37, s: 24, b: 32 },
    "Russia": { g: 32, s: 28, b: 29 },
    "China": { g: 28, s: 16, b: 14 },
    "Australia": { g: 16, s: 25, b: 17 },
    "Germany": { g: 13, s: 17, b: 26 },
    "France": { g: 13, s: 14, b: 11 },
    "Italy": { g: 13, s: 8, b: 13 },
    "Netherlands": { g: 12, s: 9, b: 4 },
    "Cuba": { g: 11, s: 11, b: 7 },
    "Great Britain": { g: 11, s: 10, b: 7 },
    "Romania": { g: 11, s: 6, b: 9 },
    "South Korea": { g: 8, s: 10, b: 10 },
    "Hungary": { g: 8, s: 6, b: 3 },
    "Poland": { g: 6, s: 5, b: 3 },
    "Japan": { g: 5, s: 8, b: 5 },
    "Bulgaria": { g: 5, s: 6, b: 2 },
    "Greece": { g: 4, s: 6, b: 3 },
    "Sweden": { g: 4, s: 5, b: 3 },
    "Norway": { g: 4, s: 3, b: 3 },
    "Ethiopia": { g: 4, s: 1, b: 3 },
    "Ukraine": { g: 3, s: 10, b: 10 },
    "Kazakhstan": { g: 3, s: 4, b: 0 },
    "Belarus": { g: 3, s: 3, b: 11 },
    "Canada": { g: 3, s: 3, b: 8 },
    "Spain": { g: 3, s: 3, b: 5 },
    "Turkey": { g: 3, s: 0, b: 2 },
    "Iran": { g: 3, s: 0, b: 1 },
    "Czech Republic": { g: 2, s: 3, b: 3 },
    "Kenya": { g: 2, s: 3, b: 2 },
    "Denmark": { g: 2, s: 3, b: 1 },
    "Finland": { g: 2, s: 1, b: 1 },
    "Austria": { g: 2, s: 1, b: 0 },
    "Lithuania": { g: 2, s: 0, b: 3 },
    "Azerbaijan": { g: 2, s: 0, b: 1 },
    "Bahamas": { g: 2, s: 0, b: 1 },
    "Slovenia": { g: 2, s: 0, b: 0 },
    "Switzerland": { g: 1, s: 6, b: 2 },
    "Indonesia": { g: 1, s: 3, b: 2 },
    "Slovakia": { g: 1, s: 3, b: 1 },
    "Mexico": { g: 1, s: 2, b: 3 },
    "Nigeria": { g: 1, s: 2, b: 0 },
    "Algeria": { g: 1, s: 1, b: 3 },
    "Uzbekistan": { g: 1, s: 1, b: 2 },
    "Latvia": { g: 1, s: 1, b: 1 },
    "New Zealand": { g: 1, s: 0, b: 3 },
    "Estonia": { g: 1, s: 0, b: 2 },
    "Thailand": { g: 1, s: 0, b: 2 },
    "Croatia": { g: 1, s: 0, b: 1 },
    "Cameroon": { g: 1, s: 0, b: 0 },
    "Colombia": { g: 1, s: 0, b: 0 },
    "Mozambique": { g: 1, s: 0, b: 0 },
    "Brazil": { g: 0, s: 6, b: 6 },
    "Jamaica": { g: 0, s: 6, b: 3 },
    "Belgium": { g: 0, s: 2, b: 3 },
    "South Africa": { g: 0, s: 2, b: 3 },
    "Argentina": { g: 0, s: 2, b: 2 },
    "Chinese Taipei": { g: 0, s: 1, b: 4 },
    "Morocco": { g: 0, s: 1, b: 4 },
    "North Korea": { g: 0, s: 1, b: 3 },
    "Moldova": { g: 0, s: 1, b: 1 },
    "Saudi Arabia": { g: 0, s: 1, b: 1 },
    "Trinidad and Tobago": { g: 0, s: 1, b: 1 },
    "Ireland": { g: 0, s: 1, b: 0 },
    "Sri Lanka": { g: 0, s: 1, b: 0 },
    "Uruguay": { g: 0, s: 1, b: 0 },
    "Vietnam": { g: 0, s: 1, b: 0 },
    "Georgia": { g: 0, s: 0, b: 6 },
    "Costa Rica": { g: 0, s: 0, b: 2 },
    "Portugal": { g: 0, s: 0, b: 2 },
    "Armenia": { g: 0, s: 0, b: 1 },
    "Barbados": { g: 0, s: 0, b: 1 },
    "Chile": { g: 0, s: 0, b: 1 },
    "Iceland": { g: 0, s: 0, b: 1 },
    "India": { g: 0, s: 0, b: 1 },
    "Israel": { g: 0, s: 0, b: 1 },
    "Kuwait": { g: 0, s: 0, b: 1 },
    "Kyrgyzstan": { g: 0, s: 0, b: 1 },
    "Macedonia": { g: 0, s: 0, b: 1 },
    "Qatar": { g: 0, s: 0, b: 1 },
  },
};